/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

package ndi

import (
	"math"
	"reflect"
	"unsafe"
)

func goStringFromConst(p uintptr) string {
	var len int
	for n := p; *(*byte)(unsafe.Pointer(n)) != 0; n++ {
		len++
	}

	h := &reflect.SliceHeader{uintptr(unsafe.Pointer(p)), len, len + 1}
	return string(*(*[]byte)(unsafe.Pointer(h)))
}

type FrameFormat int

const (
	FrameFormatInterleaved FrameFormat = iota //A fielded frame with the field 0 being on the even lines and field 1 being on the odd lines.
	FrameFormatProgressive                    //A progressive frame.

	//Individual fields.
	FrameFormatField0
	FrameFormatField1
)

var (
	FourCCTypeUYVY = [4]byte{'U', 'Y', 'V', 'Y'}

	//BGRA
	FourCCTypeBGRA = [4]byte{'B', 'G', 'R', 'A'}
	FourCCTypeBGRX = [4]byte{'B', 'G', 'R', 'X'}

	//This is a UYVY buffer followed immediately by an alpha channel buffer.
	//If the stride of the YCbCr component is "stride", then the alpha channel
	//starts at image_ptr + yres*stride. The alpha channel stride is stride/2.
	FourCCTypeUYVA = [4]byte{'U', 'Y', 'V', 'A'}
)

func NewVideoFrameV2() *VideoFrameV2 {
	vf := VideoFrameV2{}
	vf.SetDefault()
	return &vf
}

//This describes a video frame.
type VideoFrameV2 struct {
	Xres, Yres int     //The resolution of this frame.
	FourCC     [4]byte //What FourCC this is with. This can be two values.

	//What is the frame-rate of this frame.
	//For instance NTSC is 30000,1001 = 30000/1001 = 29.97fps.
	FrameRateN, FrameRateD int

	//What is the picture aspect ratio of this frame.
	//For instance 16.0/9.0 = 1.778 is 16:9 video
	//0 means square pixels.
	PictureAspectRatio float32

	//Is this a fielded frame, or is it progressive.
	FrameFormatType FrameFormat

	//The timecode of this frame in 100ns intervals.
	Timecode int64

	//The video data itself.
	Data *byte

	//The inter line stride of the video data, in bytes.
	LineStride int

	//Per frame metadata for this frame. This is a NULL terminated UTF8 string that should be
	//in XML format. If you do not want any metadata then you may specify NULL here.
	Metadata *byte

	//This is only valid when receiving a frame and is specified as a 100ns time that was the exact
	//moment that the frame was submitted by the sending side and is generated by the SDK. If this
	//value is NDIlib_recv_timestamp_undefined then this value is not available and is NDIlib_recv_timestamp_undefined.
	Timestamp int64
}

func (vf *VideoFrameV2) SetDefault() {
	vf.Xres = 0
	vf.Yres = 0
	vf.FourCC = FourCCTypeUYVA
	vf.FrameRateN = 30000
	vf.FrameRateD = 1001
	vf.PictureAspectRatio = 0
	vf.FrameFormatType = FrameFormatProgressive
	vf.Timecode = math.MaxInt64
	vf.Data = nil
	vf.LineStride = 0
	vf.Metadata = nil
	vf.Timestamp = 0
}

//This is a private struct!
type ndiLIBv3 struct {
	// V1.5
	NDIlibInitialize, //bool(*NDIlib_initialize)(void)
	NDIlibDestroy, //void(*NDIlib_destroy)(void)
	NDIlibVersion, //const char* (*NDIlib_version)(void)
	NDIlibIsSupportedCPU, //bool(*NDIlib_is_supported_CPU)(void)
	NDIlibFindCreate, //PROCESSINGNDILIB_DEPRECATED NDIlib_find_instance_t(*NDIlib_find_create)(const NDIlib_find_create_t* p_create_settings)
	NDIlibFindCreateV2, //NDIlib_find_instance_t(*NDIlib_find_create_v2)(const NDIlib_find_create_t* p_create_settings)
	NDIlibFindDestroy, //void(*NDIlib_find_destroy)(NDIlib_find_instance_t p_instance)
	NDIlibFindGetSources, //const NDIlib_source_t* (*NDIlib_find_get_sources)(NDIlib_find_instance_t p_instance, uint32_t* p_no_sources, uint32_t timeout_in_ms)
	NDIlibSendCreate, //NDIlib_send_instance_t(*NDIlib_send_create)(const NDIlib_send_create_t* p_create_settings)
	NDIlibSendDestroy, //void(*NDIlib_send_destroy)(NDIlib_send_instance_t p_instance)
	NDIlibSendSendVideo, //PROCESSINGNDILIB_DEPRECATED void(*NDIlib_send_send_video)(NDIlib_send_instance_t p_instance, const NDIlib_video_frame_t* p_video_data)
	NDIlibSendSendVideoAsync, //PROCESSINGNDILIB_DEPRECATED void(*NDIlib_send_send_video_async)(NDIlib_send_instance_t p_instance, const NDIlib_video_frame_t* p_video_data)
	NDIlibSendSendAudio, //PROCESSINGNDILIB_DEPRECATED void(*NDIlib_send_send_audio)(NDIlib_send_instance_t p_instance, const NDIlib_audio_frame_t* p_audio_data)
	NDIlibSendSendMetadata, //void(*NDIlib_send_send_metadata)(NDIlib_send_instance_t p_instance, const NDIlib_metadata_frame_t* p_metadata)
	NDIlibSendCapture, //NDIlib_frame_type_e(*NDIlib_send_capture)(NDIlib_send_instance_t p_instance, NDIlib_metadata_frame_t* p_metadata, uint32_t timeout_in_ms)
	NDIlibSendFreeMetadata, //void(*NDIlib_send_free_metadata)(NDIlib_send_instance_t p_instance, const NDIlib_metadata_frame_t* p_metadata)
	NDIlibSendGetTally, //bool(*NDIlib_send_get_tally)(NDIlib_send_instance_t p_instance, NDIlib_tally_t* p_tally, uint32_t timeout_in_ms)
	NDIlibSendGetNoConnections, //int(*NDIlib_send_get_no_connections)(NDIlib_send_instance_t p_instance, uint32_t timeout_in_ms)
	NDIlibSendClearConnectionMetadata, //void(*NDIlib_send_clear_connection_metadata)(NDIlib_send_instance_t p_instance)
	NDIlibSendAddConnectionMetadata, //void(*NDIlib_send_add_connection_metadata)(NDIlib_send_instance_t p_instance, const NDIlib_metadata_frame_t* p_metadata)
	NDIlibSendSetFailover, //void(*NDIlib_send_set_failover)(NDIlib_send_instance_t p_instance, const NDIlib_source_t* p_failover_source)
	NDIlibRecvCreateV2, //NDIlib_recv_instance_t(*NDIlib_recv_create_v2)(const NDIlib_recv_create_t* p_create_settings)
	NDIlibRecvCreate, //NDIlib_recv_instance_t(*NDIlib_recv_create)(const NDIlib_recv_create_t* p_create_settings)
	NDIlibRecvDestroy, //void(*NDIlib_recv_destroy)(NDIlib_recv_instance_t p_instance)
	NDIlibRecvCapture, //PROCESSINGNDILIB_DEPRECATED NDIlib_frame_type_e(*NDIlib_recv_capture)(NDIlib_recv_instance_t p_instance, NDIlib_video_frame_t* p_video_data, NDIlib_audio_frame_t* p_audio_data, NDIlib_metadata_frame_t* p_metadata, uint32_t timeout_in_ms)
	NDIlibRecvFreeVideo, //PROCESSINGNDILIB_DEPRECATED void(*NDIlib_recv_free_video)(NDIlib_recv_instance_t p_instance, const NDIlib_video_frame_t* p_video_data)
	NDIlibRecvFreeAudio, //PROCESSINGNDILIB_DEPRECATED void(*NDIlib_recv_free_audio)(NDIlib_recv_instance_t p_instance, const NDIlib_audio_frame_t* p_audio_data)
	NDIlibRecvFreeMetadata, //void(*NDIlib_recv_free_metadata)(NDIlib_recv_instance_t p_instance, const NDIlib_metadata_frame_t* p_metadata)
	NDIlibRecvSendMetadata, //bool(*NDIlib_recv_send_metadata)(NDIlib_recv_instance_t p_instance, const NDIlib_metadata_frame_t* p_metadata)
	NDIlibRecvSetTally, //bool(*NDIlib_recv_set_tally)(NDIlib_recv_instance_t p_instance, const NDIlib_tally_t* p_tally)
	NDIlibRecvGetPerformance, //void(*NDIlib_recv_get_performance)(NDIlib_recv_instance_t p_instance, NDIlib_recv_performance_t* p_total, NDIlib_recv_performance_t* p_dropped)
	NDIlibRecvGetQueue, //void(*NDIlib_recv_get_queue)(NDIlib_recv_instance_t p_instance, NDIlib_recv_queue_t* p_total)
	NDIlibRecvClearConnectionMetadata, //void(*NDIlib_recv_clear_connection_metadata)(NDIlib_recv_instance_t p_instance)
	NDIlibRecvAddConnectionMetadata, //void(*NDIlib_recv_add_connection_metadata)(NDIlib_recv_instance_t p_instance, const NDIlib_metadata_frame_t* p_metadata)
	NDIlibRecvGetNoConnections, //int(*NDIlib_recv_get_no_connections)(NDIlib_recv_instance_t p_instance)
	NDIlibRoutingCreate, //NDIlib_routing_instance_t(*NDIlib_routing_create)(const NDIlib_routing_create_t* p_create_settings)
	NDIlibRoutingDestroy, //void(*NDIlib_routing_destroy)(NDIlib_routing_instance_t p_instance)
	NDIlibRoutingChange, //bool(*NDIlib_routing_change)(NDIlib_routing_instance_t p_instance, const NDIlib_source_t* p_source)
	NDIlibRoutingClear, //bool(*NDIlib_routing_clear)(NDIlib_routing_instance_t p_instance)
	NDIlibUtilSendSendAudioInterleaved16s, //void(*NDIlib_util_send_send_audio_interleaved_16s)(NDIlib_send_instance_t p_instance, const NDIlib_audio_frame_interleaved_16s_t* p_audio_data)
	NDIlibUtilAudioToInterleaved16s, //PROCESSINGNDILIB_DEPRECATED void(*NDIlib_util_audio_to_interleaved_16s)(const NDIlib_audio_frame_t* p_src, NDIlib_audio_frame_interleaved_16s_t* p_dst)
	NDIlibUtilAudioFromInterleaved16s, //PROCESSINGNDILIB_DEPRECATED void(*NDIlib_util_audio_from_interleaved_16s)(const NDIlib_audio_frame_interleaved_16s_t* p_src, NDIlib_audio_frame_t* p_dst)

	// V2
	NDIlibFindWaitForSources, //bool(*NDIlib_find_wait_for_sources)(NDIlib_find_instance_t p_instance, uint32_t timeout_in_ms)
	NDIlibFindGetCurrentSources, //const NDIlib_source_t* (*NDIlib_find_get_current_sources)(NDIlib_find_instance_t p_instance, uint32_t* p_no_sources)
	NDIlibUtilAudioToInterleaved32f, //PROCESSINGNDILIB_DEPRECATED void(*NDIlib_util_audio_to_interleaved_32f)(const NDIlib_audio_frame_t* p_src, NDIlib_audio_frame_interleaved_32f_t* p_dst)
	NDIlibUtilAudioFromInterleaved32f, //PROCESSINGNDILIB_DEPRECATED void(*NDIlib_util_audio_from_interleaved_32f)(const NDIlib_audio_frame_interleaved_32f_t* p_src, NDIlib_audio_frame_t* p_dst)
	NDIlibUtilSendSendAudioInterleaved32f, //void(*NDIlib_util_send_send_audio_interleaved_32f)(NDIlib_send_instance_t p_instance, const NDIlib_audio_frame_interleaved_32f_t* p_audio_data)

	// V3
	NDIlibRecvFreeVideoV2, //void(*NDIlib_recv_free_video_v2)(NDIlib_recv_instance_t p_instance, const NDIlib_video_frame_v2_t* p_video_data)
	NDIlibRecvFreeAudioV2, //void(*NDIlib_recv_free_audio_v2)(NDIlib_recv_instance_t p_instance, const NDIlib_audio_frame_v2_t* p_audio_data)
	NDIlibRecvCaptureV2, //NDIlib_frame_type_e(*NDIlib_recv_capture_v2)(NDIlib_recv_instance_t p_instance, NDIlib_video_frame_v2_t* p_video_data, NDIlib_audio_frame_v2_t* p_audio_data, NDIlib_metadata_frame_t* p_metadata, uint32_t timeout_in_ms)
	NDIlibSendSendVideoV2, //void(*NDIlib_send_send_video_v2)(NDIlib_send_instance_t p_instance, const NDIlib_video_frame_v2_t* p_video_data)
	NDIlibSendSendVideoAsyncV2, //void(*NDIlib_send_send_video_async_v2)(NDIlib_send_instance_t p_instance, const NDIlib_video_frame_v2_t* p_video_data)
	NDIlibSendSendAudioV2, //void(*NDIlib_send_send_audio_v2)(NDIlib_send_instance_t p_instance, const NDIlib_audio_frame_v2_t* p_audio_data)
	NDIlibUtilAudioToInterleaved16sV2, //void(*NDIlib_util_audio_to_interleaved_16s_v2)(const NDIlib_audio_frame_v2_t* p_src, NDIlib_audio_frame_interleaved_16s_t* p_dst)
	NDIlibUtilAudioFromInterleaved16sV2, //void(*NDIlib_util_audio_from_interleaved_16s_v2)(const NDIlib_audio_frame_interleaved_16s_t* p_src, NDIlib_audio_frame_v2_t* p_dst)
	NDIlibUtilAudioToInterleaved32fV2, //void(*NDIlib_util_audio_to_interleaved_32f_v2)(const NDIlib_audio_frame_v2_t* p_src, NDIlib_audio_frame_interleaved_32f_t* p_dst)
	NDIlibUtilAudioFromInterleaved32fV2, //void(*NDIlib_util_audio_from_interleaved_32f_v2)(const NDIlib_audio_frame_interleaved_32f_t* p_src, NDIlib_audio_frame_v2_t* p_dst)

	// V3.01
	NDIlibRecvFreeString, //void(*NDIlib_recv_free_string)(NDIlib_recv_instance_t p_instance, const char* p_string)
	NDIlibRecvPtzIsSupported, //bool(*NDIlib_recv_ptz_is_supported)(NDIlib_recv_instance_t p_instance)
	NDIlibRecvRecordingIsSupported, //bool(*NDIlib_recv_recording_is_supported)(NDIlib_recv_instance_t p_instance)
	NDIlibRecvGetWebControl, //const char*(*NDIlib_recv_get_web_control)(NDIlib_recv_instance_t p_instance)
	NDIlibRecvPtzZoom, //bool(*NDIlib_recv_ptz_zoom)(NDIlib_recv_instance_t p_instance, const float zoom_value)
	NDIlibRecvPtzZoomSpeed, //bool(*NDIlib_recv_ptz_zoom_speed)(NDIlib_recv_instance_t p_instance, const float zoom_speed)
	NDIlibRecvPtzPanTilt, //bool(*NDIlib_recv_ptz_pan_tilt)(NDIlib_recv_instance_t p_instance, const float pan_value, const float tilt_value)
	NDIlibRecvPtzPanTiltSpeed, //bool(*NDIlib_recv_ptz_pan_tilt_speed)(NDIlib_recv_instance_t p_instance, const float pan_speed, const float tilt_speed)
	NDIlibRecvPtzStorePreset, //bool(*NDIlib_recv_ptz_store_preset)(NDIlib_recv_instance_t p_instance, const int preset_no)
	NDIlibRecvPtzRecallPreset, //bool(*NDIlib_recv_ptz_recall_preset)(NDIlib_recv_instance_t p_instance, const int preset_no, const float speed)
	NDIlibRecvPtzAutoFocus, //bool(*NDIlib_recv_ptz_auto_focus)(NDIlib_recv_instance_t p_instance)
	NDIlibRecvPtzFocus, //bool(*NDIlib_recv_ptz_focus)(NDIlib_recv_instance_t p_instance, const float focus_value)
	NDIlibRecvPtzFocusSpeed, //bool(*NDIlib_recv_ptz_focus_speed)(NDIlib_recv_instance_t p_instance, const float focus_speed)
	NDIlibRecvPtzWhiteBalanceAuto, //bool(*NDIlib_recv_ptz_white_balance_auto)(NDIlib_recv_instance_t p_instance)
	NDIlibRecvPtzWhiteBalanceIndoor, //bool(*NDIlib_recv_ptz_white_balance_indoor)(NDIlib_recv_instance_t p_instance)
	NDIlibRecvPtzWhiteBalanceOutdoor, //bool(*NDIlib_recv_ptz_white_balance_outdoor)(NDIlib_recv_instance_t p_instance)
	NDIlibRecvPtzWhiteBalanceOneshot, //bool(*NDIlib_recv_ptz_white_balance_oneshot)(NDIlib_recv_instance_t p_instance)
	NDIlibRecvPtzWhiteBalanceManual, //bool(*NDIlib_recv_ptz_white_balance_manual)(NDIlib_recv_instance_t p_instance, const float red, const float blue)
	NDIlibRecvPtzExposureAuto, //bool(*NDIlib_recv_ptz_exposure_auto)(NDIlib_recv_instance_t p_instance)
	NDIlibRecvPtzExposureManual, //bool(*NDIlib_recv_ptz_exposure_manual)(NDIlib_recv_instance_t p_instance, const float exposure_level)
	NDIlibRecvRecordingStart, //bool(*NDIlib_recv_recording_start)(NDIlib_recv_instance_t p_instance, const char* p_filename_hint)
	NDIlibRecvRecordingStop, //bool(*NDIlib_recv_recording_stop)(NDIlib_recv_instance_t p_instance)
	NDIlibRecvRecordingSetAudioLevel, //bool(*NDIlib_recv_recording_set_audio_level)(NDIlib_recv_instance_t p_instance, const float level_dB)
	NDIlibRecvRecordingIsRecording, //bool(*NDIlib_recv_recording_is_recording)(NDIlib_recv_instance_t p_instance)
	NDIlibRecvRecordingGetFilename, //const char*(*NDIlib_recv_recording_get_filename)(NDIlib_recv_instance_t p_instance)
	NDIlibRecvRecordingGetError, //const char*(*NDIlib_recv_recording_get_error)(NDIlib_recv_instance_t p_instance)
	NDIlibRecvRecordingGetTimes uintptr //bool(*NDIlib_recv_recording_get_times)(NDIlib_recv_instance_t p_instance, NDIlib_recv_recording_time_t* p_times)
}
